version: "3.9"

services:
  flask:
    image: python:3.12-slim
    # container_name: flask_app
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_ENV=development
    command: >
      sh -c "pip install flask &&
             flask run"
